services:
  app:
    build: 
    container_name: hola_mundo_app
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=hola_mundo_db
      - DB_USER=postgres
      - DB_PASSWORD=password123
    networks:
      - app_network

  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=hola_mundo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
